name: carmarketplace
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  firebase_storage: ^12.4.5
  http: ^0.13.6
  intl: ^0.18.1

  pdf: ^3.10.4
  printing: ^5.11.0
  excel: ^2.0.5
  path_provider: ^2.1.2
  provider: ^6.1.5
  flutter_swiper_view: ^1.1.6 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - image/
