// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZZe7mnSLR9Ha0yLktb0S7ZhH00V7no0',
    appId: '1:713769116125:web:172460203e9700292cd634',
    messagingSenderId: '713769116125',
    projectId: 'carauth-ea665',
    authDomain: 'carauth-ea665.firebaseapp.com',
    storageBucket: 'carauth-ea665.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJSbDy9iwfEfOXnTbmFNUt5yOqmZ_J3AE',
    appId: '1:713769116125:android:57f2c3dc39e2d0732cd634',
    messagingSenderId: '713769116125',
    projectId: 'carauth-ea665',
    storageBucket: 'carauth-ea665.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBExU2Q6bpUbgeI1MogDKu61-364pzpAv0',
    appId: '1:713769116125:ios:b3e8b4840d8b7b292cd634',
    messagingSenderId: '713769116125',
    projectId: 'carauth-ea665',
    storageBucket: 'carauth-ea665.firebasestorage.app',
    iosBundleId: 'com.example.carmarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBExU2Q6bpUbgeI1MogDKu61-364pzpAv0',
    appId: '1:713769116125:ios:b3e8b4840d8b7b292cd634',
    messagingSenderId: '713769116125',
    projectId: 'carauth-ea665',
    storageBucket: 'carauth-ea665.firebasestorage.app',
    iosBundleId: 'com.example.carmarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqZZe7mnSLR9Ha0yLktb0S7ZhH00V7no0',
    appId: '1:713769116125:web:ca5096720d30c7202cd634',
    messagingSenderId: '713769116125',
    projectId: 'carauth-ea665',
    authDomain: 'carauth-ea665.firebaseapp.com',
    storageBucket: 'carauth-ea665.firebasestorage.app',
  );
}
