import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:flutter/services.dart' show Uint8List, rootBundle; // Required for font loading
import 'package:intl/intl.dart';
import 'package:cloud_firestore/cloud_firestore.dart'; // To handle Timestamp conversion

class PdfRentalInvoiceService {
  Future<Uint8List> generateRentalInvoicePdf(Map<String, dynamic> rentalData) async {
    final pdf = pw.Document();

    // Load a font that supports a wider range of characters, if needed.
    // For simplicity, we'll use a built-in font for now.
    // If you need custom fonts (e.g., for non-Latin characters), you'd load them like this:
    // final font = await PdfGoogleFonts.openSansRegular(); // Requires 'pdf_google_fonts' package

    // Extract data with null checks and default values
    final String carName = rentalData['carName'] ?? 'N/A';
    final double rentPrice = rentalData['rentPrice'] ?? 0.0;
    final double totalPrice = rentalData['totalPrice'] ?? 0.0;
    final int days = rentalData['days'] ?? 0;
    final String customerName = rentalData['customerName'] ?? 'N/A';
    final String customerContact = rentalData['customerContact'] ?? 'N/A';
    final String paymentNumber = rentalData['paymentNumber'] ?? 'N/A';
    final String paymentReference = rentalData['paymentReference'] ?? 'N/A';
    
    // Safely convert Timestamp to DateTime
    final DateTime startDate = (rentalData['startDate'] is Timestamp)
        ? (rentalData['startDate'] as Timestamp).toDate()
        : DateTime.now(); // Default if not a Timestamp
    final DateTime endDate = (rentalData['endDate'] is Timestamp)
        ? (rentalData['endDate'] as Timestamp).toDate()
        : DateTime.now(); // Default if not a Timestamp
    final DateTime createdAt = (rentalData['createdAt'] is Timestamp)
        ? (rentalData['createdAt'] as Timestamp).toDate()
        : DateTime.now(); // Default if not a Timestamp


    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Center(
                child: pw.Text(
                  'Rental Invoice',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Invoice Date: ${DateFormat('yyyy-MM-dd HH:mm').format(createdAt)}'),
              pw.SizedBox(height: 10),
              pw.Divider(),
              pw.SizedBox(height: 10),

              pw.Text(
                'Customer Details:',
                style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
              ),
              pw.Text('Name: $customerName'),
              pw.Text('Contact: $customerContact'),
              pw.Text('Payment Number: $paymentNumber'),
              pw.SizedBox(height: 20),

              pw.Text(
                'Rental Details:',
                style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
              ),
              pw.Text('Car: $carName'),
              pw.Text('Rental Price per Day: \$${rentPrice.toStringAsFixed(2)}'),
              pw.Text('Start Date: ${DateFormat('MMM d, yyyy').format(startDate)}'),
              pw.Text('End Date: ${DateFormat('MMM d, yyyy').format(endDate)}'),
              pw.Text('Number of Days: $days'),
              pw.SizedBox(height: 20),

              pw.Text(
                'Payment Details:',
                style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
              ),
              pw.Text('Payment Method: EVC Plus'),
              pw.Text('Transaction ID: $paymentReference'),
              pw.SizedBox(height: 10),
              pw.Text(
                'Amount Paid: \$${totalPrice.toStringAsFixed(2)}',
                style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 30),

              pw.Center(
                child: pw.Text(
                  'Thank you for your rental!',
                  style: pw.TextStyle(fontSize: 18, fontStyle: pw.FontStyle.italic),
                ),
              ),
               pw.Spacer(), // Pushes the footer to the bottom
              pw.Center(
                child: pw.Text(
                  'Generated by CarMarketplace App',
                  style: pw.TextStyle(fontSize: 10, color: PdfColors.grey),
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }
}